// Action types
export const GET_EXERCISES_REQUEST = "GET_EXERCISES_REQUEST";
export const GET_EXERCISES_SUCCESS = "GET_EXERCISES_SUCCESS";
export const GET_EXERCISES_FAILURE = "GET_EXERCISES_FAILURE";

export const ADD_EXERCISE_REQUEST = "ADD_EXERCISE_REQUEST";
export const ADD_EXERCISE_SUCCESS = "ADD_EXERCISE_SUCCESS";
export const ADD_EXERCISE_FAILURE = "ADD_EXERCISE_FAILURE";

export const DELETE_EXERCISE_REQUEST = "DELETE_EXERCISE_REQUEST";
export const DELETE_EXERCISE_SUCCESS = "DELETE_EXERCISE_SUCCESS";
export const DELETE_EXERCISE_FAILURE = "DELETE_EXERCISE_FAILURE";
